@startuml
title TicketingSystem Use Case Diagram
left to right direction
'https://plantuml.com/use-case-diagram

:Main Admin: as Admin
:Main OfficeWorker: as OfficeWorker
:Main User: as User

User <|- OfficeWorker
OfficeWorker <|- Admin


rectangle WebApplication {
OfficeWorker -> (Reject ticket)
OfficeWorker -> (Mark as duplicate)
OfficeWorker -> (Forward ticket)
OfficeWorker -> (Close ticket)
OfficeWorker -> (Change ticket status)



User --> (Browse tickets)
User --> (Add comment)
User --> (Create ticket)
User --> (Log in)
(Browse tickets) <.. (Filter): <extends>
(Browse tickets) <.. (Sort): <extends>


Admin --> (Assign Privileges)
Admin --> (Delete Ticket)

}


@enduml